### ISSUE TITLE
Possilvel erro na classe Professor

### ISSUE THREAD

**Issue by msantos7gabriel** [guilherme-nunes-x/ASW#1]
Partindo do presuposto que Cadeira e Carteiras são a mesma coisa o atributo dessa classe está duplicado.
Caso o presuposto esteja errado, peço que disconsidere essa Issue. 

![image](https://github.com/guilherme-nunes-x/ASW/assets/113394709/610f6bb6-137a-4bfd-ba42-287919821710)

**Comment by guilherme-nunes-x** [comment]
Obrigado por essa ideia e já pretendo modificar e corrigir
